version: '3'
services:
  nginx:
    container_name: nginx
    build:
        context: dockerfiles/nginx
        dockerfile: Dockerfile
    ports:
        - 80:8000

  utorrent:
    image: ekho/utorrent:latest
    container_name: utorrent
    volumes:
      - ~/utorrent/data:/utorrent/data
      - utorrent-settings:/utorrent/settings
      - ~/utorrent/torrent-files/utserver.conf:/utorrent/utserver.conf
    environment:
      HOST_UID: 1002
      HOST_GID: 1002
    ports:
      - 8080:8080
      - 6881:6881
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Africa/Johannesburg
      - ADVERTISE_IP=http://192.168.8.102:32400/
    hostname: foecum.plex
    volumes:
      - ~/plex/database:/config
      - ~/plex/transcode/tmp:/transcode
      - /media/data:/data/media

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  utorrent-settings:
  portainer_data: